import React from 'react'

export default function options() {
    return (
    <>
        <option>AED</option>
        <option>AFN</option>
        <option>ALL</option>        
        <option>AMD</option>
        <option>ANG</option>
        <option>AOA</option>
        <option>ARS</option>
        <option>AUD</option>
        <option>AWG</option>
        <option>AZN</option>
        <option>BAM</option>
        <option>BBD</option>
        <option>BDT</option>
        <option>BGN</option>
        <option>BHD</option>
        <option>BIF</option>
        <option>BMD</option>
        <option>BND</option>
        <option>BOB</option>
        <option>BRL</option>
        <option>BSD</option>
        <option>BTC</option>
        <option>BTN</option>
        <option>BWP</option>
        <option>BYN</option>
        <option>BYR</option>
        <option>BZD</option>
        <option>CAD</option>
        <option>CDF</option>
        <option>CHF</option>
        <option>CLF</option>
        <option>CLP</option>
        <option>CNY</option>
        <option>COP</option>
        <option>CRC</option> 
        <option>CUC</option> 
        <option>CUP</option>
        <option>CVE</option>
        <option>CZK</option>
        <option>DJF</option>
        <option>DKK</option>
        <option>DOP</option>
        <option>DZD</option>
        <option>EGP</option>
        <option>ERN</option>
        <option>ETB</option>
        <option>EUR</option>
        <option>FJD</option>
        <option>FKP</option>
        <option>GBP</option> 
        <option>GEL</option> 
        <option>GGP</option>
        <option>GHS</option> 
        <option>GIP</option>
        <option>GMD</option>
        <option>GNF</option>
        <option>GTQ</option>
        <option>GYD</option> 
        <option>HKD</option>
        <option>HNL</option> 
        <option>HRK</option> 
        <option>HTG</option> 
        <option>HUF</option> 
        <option>IDR</option> 
        <option>ILS</option>
        <option>IMP</option>
        <option>INR</option>
        <option>IQD</option>
        <option>IRR</option>
        <option>ISK</option>
        <option>JEP</option>
        <option>JMD</option>
        <option>JOD</option>
        <option>JPY</option>
        <option>KES</option>
        <option>KGS</option>
        <option>KHR</option>
        <option>KMF</option>
        <option>KPW</option>
        <option>KRW</option>
        <option>KWD</option>
        <option>KYD</option>
        <option>KZT</option>
        <option>LAK</option>
        <option>LBP</option>
        <option>LKR</option>
        <option>LRD</option>
        <option>LSL</option>
        <option>LTL</option>
        <option>LVL</option>
        <option>LYD</option>
        <option>MAD</option>
        <option>MDL</option>
        <option>MGA</option>
        <option>MKD</option>
        <option>MMK</option>
        <option>MNT</option>
        <option>MOP</option>
        <option>MRO</option>
        <option>MUR</option>
        <option>MVR</option>
        <option>MWK</option>
        <option>MXN</option>
        <option>MYR</option>
        <option>MZN</option>
        <option>NAD</option>
        <option>NGN</option>
        <option>NIO</option> 
        <option>NOK</option> 
        <option>NPR</option>
        <option>NZD</option>
        <option>OMR</option>
        <option>PAB</option>
        <option>PEN</option>
        <option>PGK</option>
        <option>PHP</option> 
        <option>PKR</option>
        <option>PLN</option>
        <option>PYG</option>
        <option>QAR</option>
        <option>RON</option>
        <option>RSD</option>
        <option>RUB</option> 
        <option>RWF</option>
        <option>SAR</option>
        <option>SBD</option>
        <option>SCR</option> 
        <option>SDG</option>
        <option>SEK</option> 
        <option>SGD</option>
        <option>SHP</option>
        <option>SLL</option>
        <option>SOS</option>
        <option>SRD</option> 
        <option>STD</option>
        <option>SVC</option> 
        <option>SYP</option>
        <option>SZL</option> 
        <option>THB</option> 
        <option>TJS</option> 
        <option>TMT</option>
        <option>TND</option>
        <option>TOP</option>
        <option>TRY</option>
        <option>TTD</option>
        <option>TWD</option> 
        <option>TZS</option>
        <option>UAH</option> 
        <option>UGX</option>
        <option>USD</option>
        <option>UYU</option> 
        <option>UZS</option>
        <option>VEF</option> 
        <option>VND</option>
        <option>VUV</option>
        <option>WST</option>
        <option>XAF</option>
        <option>XAG</option>
        <option>XAU</option>
        <option>XCD</option>
        <option>XDR</option>
        <option>XOF</option>
        <option>XPF</option>
        <option>YER</option>
        <option>ZAR</option> 
        <option>ZMK</option> 
        <option>ZMW</option>
        <option>ZWL</option>
    </>
    )
}